version: '3'
services:
  app:
    build: ./docker/app
    tty: true
    privileged: true
    environment:
      # - DISPLAY=${DISPLAY}
      # 以下でコンテナ側にディスプレイ設定が反映されるっぽい?
      - DISPLAY=host.docker.internal:0
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/home/docker/app